name: Export

on:
  push:
  pull_request:

jobs:
  export:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inti-cmnb/kicad7_auto:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run kibot
        run: kibot -vvv
      - name: Archive Gerber ZIP
        uses: actions/upload-artifact@v2
        with:
          name: jlc
          path: JLCPCB/*.zip
      - name: Archive Positions/BOM
        uses: actions/upload-artifact@v2
        with:
          name: jlc
          path: "samd21pad*jlc.csv"
